---
title: 2. pytorch数据预处理
date: 2023-11-27 14:00:00
tags: [深度学习,机器学习,pytorch,数据预处理]
categories: [深度学习]
comment: false
toc: true
---
######
<!--more-->
# 3. 线性代数
## 3.1 标量


In [3]:
import torch

x=torch.tensor(3.0)

## 3.2 向量

In [4]:
x=torch.arange(4)

#1 取值
print(x[3])

#2 长度
print(len(x))
print(x.shape)

tensor(3)
4
torch.Size([4])


## 3.3 矩阵


In [6]:
A=torch.arange(20).reshape(5,4) #矩阵用大写字母
print(A)

#1 转置
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


## 3.4 张量

In [10]:
X= torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 3.5 张量算法的基本性质

In [23]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)

#1 复制
B=A.clone()
print(A==B)

#2 Hadamard积⊙ (对应位置相乘)
print(A*B)

#3 张量+标量（所有元素加上标量）
print(A+2)

#4 元素个数
print(A.numel())

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])
20


## 3.6 降维

In [34]:
X= torch.arange(4,dtype=torch.float32).reshape(2,2)

#1 按轴求和
print(X.sum(axis=0)) #压缩掉第0维

#2 按轴求平均
print(X.mean(axis=0))

#3 非降维求和
sum_X=X.sum(axis=0,keepdims=True)
print(sum_X) #还是二维，只是第0维的长度为1

#4 沿某个轴计算A元素的累积总和
print(A.cumsum(axis=0))

tensor([2., 4.])
tensor([1., 2.])
tensor([[2., 4.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


## 3.7 点积
- $$<x,y>= x^Ty= \Sigma^{d}_{i=1}x_iy_i$$

In [36]:
x=y=torch.arange(4,dtype=torch.float32)
print(x,y,torch.dot(x,y),sep='\n')

tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.])
tensor(14.)


## 3.8 矩阵-向量积

In [41]:
print(A)
print(x)
torch.mv(A,x) #输出是【5，1】但是1被压缩

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([0., 1., 2., 3.])


tensor([ 14.,  38.,  62.,  86., 110.])

## 3.9 矩阵-矩阵乘法


In [43]:
print(A)
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 3.10 范数
- 表示一个向量有多大。这里考虑的大小概念不涉及维度，而是分量的大小。
### 3.10.1 向量范数
- 将向量x映射到标量的函数$f$。
- 向量范数必须满足以下性质：
    - 】    